// glossaryファイル Cognitive_bias
`use strict`
const glossary = [
{target:`主体の察知（Agent detection）`, content:`そこに意志あるものが存在しているという思い込み。`},
{target:`曖昧性効果（Ambiguity effect）`, content:`情報が不足している選択肢は避ける傾向。`},
{target:`アンカリング（Anchoring or focalism）`, content:`先行する何らかの数値（アンカー）によって後の数値の判断が歪められ、判断された数値がアンカーに近づく傾向のことをさす。`},
{target:`人間中心主義（Anthropocentrism）`, content:`動物、物体、抽象的概念などの特徴を人間の感情や行動等に例える傾向。`},
{target:`プロスペクト理論（Prospect theory）`, content:`不確実な状況における意思決定モデルであり、（１）得することより損をしないことを選ぶ傾向、（２）損も得も量が増えるとインパクトが弱まっていく傾向、などを説明するもの。`},
{target:`注目バイアス（Attentional bias）`, content:`繰り返し思考する概念については、より注意して観察する傾向。`},
{target:`属性置換（Attribute substitution）`, content:`計算が複雑な属性を判断しなければならないときに、より計算しやすいヒューリスティックな属性で代用してしまうこと。`},
{target:`自動化バイアス（Automation bias）`, content:`自動化された意思決定システムによる指示には従うが、自動化されていない指示には、たとえそれが正しくても従わない傾向。`},
{target:`利用可能性ヒューリスティック（Availability heuristic）`, content:`認識、理解、決定の際に、思い出しやすい情報だけに基づいて判断する傾向。`},
{target:`バックファイア効果（Backfire effect）`, content:`他者が不当性を証明しようとすると、逆にますます信念を深める傾向。（その後のメタ分析で否定的な結論が出ています。）`},
{target:`基準率の錯誤（Base rate fallacy）`, content:`イメージしやすい特殊な数字には敏感に反応する一方で、統計的な一般的な数字は無視する傾向。`},
{target:`信念バイアス（Belief bias）`, content:`論理的に正しいが信念に反する主張よりも、論理的に間違っているが信念に合致する主張を信じる傾向。`},
{target:`バークソンのパラドックス（Berkson's paradox）`, content:`一部を欠落したデータを無自覚に使うことで、真実を歪めた統計結果を生み出してしまう傾向。`},
{target:`クラスター錯覚（Clustering illusion）`, content:`ランダムな現象に一定の法則があるように錯覚する傾向。`},
{target:`コンパッション・フェード（Compassion fade）`, content:`助けを必要としている人の数が増えると、共感性が低下する傾向。`},
{target:`確証バイアス（Confirmation bias）`, content:`頭が良い人ほど陥りやすい認知バイアス。`},
{target:`適合バイアス（Congruence bias）`, content:`仮説や信念を検証する際にそれを支持する情報ばかりを集め、反証する情報を無視または集めようとしない傾向。`},
{target:`合接の誤謬（conjunction fallacy）`, content:`特殊なケースの方が一般的なケースより起こりやすいと考える錯覚。`},
{target:`保守性バイアス（Conservatism Bias）`, content:`新しい証拠が提示されても自分の信念を十分に修正しない傾向。`},
{target:`誤信の継続的影響（the continued influence of misinformation）`, content:`間違った信念が、訂正された後も持続する傾向。`},
{target:`コントラスト効果（Contrast effect）`, content:`事前に得た刺激により、対象への評価が変わること。`},
{target:`知識の呪い`, content:`自分の知っていることは、他の人も知っていると思い込む傾向。`},
{target:`凋落主義（Declinism）`, content:`社会や組織が凋落しつつあると考える。過去を美化し、将来を悲観する傾向。`},
{target:`おとり効果（Decoy effect）`, content:`実際には選ばれる事のない選択肢を混入させる事によって、意志決定が変わる効果。`},
{target:`デフォルト効果（Default effect）`, content:`複数の選択肢が与えられた場合、デフォルトのものを好む傾向。`},
{target:`額面効果（Denomination effect）`, content:`同じ金額でも小さい額面のお金のほうが大きな額面のお金より使ってしまう傾向。`},
{target:`ディスポジション効果（Disposition effect）`, content:`株などの資産が値上がりした時には売りたがるが、値下がりした時には売りたがらない傾向。`},
{target:`区別バイアス（Distinction bias）`, content:`二つ選択肢を別の機会に評価すると似ていると感じるが、同時に評価すると似ていないと感じる傾向。`},
{target:`ホットハンドの誤謬（Hot-hand fallacy）`, content:`賭博など、ランダムなイベントでうまく行くと、次もうまく行くと考えてやめられなくなる傾向。`},
{target:`ダニング=クルーガー効果（Dunning–Kruger effect）`, content:`知識がない人ほど自分に知識があると思い込む傾向。また知識が増えると自信が減る傾向。`},
{target:`持続の軽視（Duration neglect）`, content:`不快な事件について、どれだけ不快な期間が持続したかをあまり問題にしない傾向。`},
{target:`望遠鏡効果（Telescoping effect）`, content:`最近の出来事がより昔に、昔の出来事をより最近あったことと思い込む傾向。`},
{target:`感情移入ギャップ（Empathy gap）`, content:`怒ったり恋愛したりしている時に、その感情を持たない視点で考える事ができない傾向。ある感情にいないとき、その感情がある状態を想像できないこと。`},
{target:`歴史の終わり錯覚（End-of-history illusion）`, content:`年齢を問わず、自分は現在までに大きな変化をしてきたが、今後は大きく成長したり成熟したりすることはないと考える心理的錯覚。`},
{target:`保有効果（Endowment effect）`, content:`一度何かを所有すると、それを手に入れる以前に支払ってもいいと思っていた以上の犠牲を払ってでも、それを手放したがらない傾向。`},
{target:`誇張された予想（Exaggerated expectation）`, content:`現実世界は予想していたよりも、普通である傾向。`},
{target:`実験者バイアス（Experimenter bias）`, content:`自分の予測と一致するデータを重視し、反するデータを無視する傾向。または実験者の期待が被験者（実験対象者）の行動に及ぼしてしまう影響。`},
{target:`バーナム効果（Barnum effect）`, content:`誰にでも該当するような曖昧で一般的な性格をあらわす記述を、自分だけに当てはまる正確なものだと捉えてしまう傾向。`},
{target:`フレーミング効果（Framing effect）`, content:`情報の提示の仕方で、同じ情報から異なる結論を引き出す効果。`},
{target:`頻度錯誤（Frequency illusion）`, content:`一旦気にし始めると、急にそれを頻繁に目にするようになる錯覚。日本においてのみ「カラーバス効果」と呼ばれているものは、この認知バイアスに相当。`},
{target:`機能的固定 (Functional fixedness)`, content:`ある物を伝統的な方法でしか使用できないように制限して考えてしまう傾向。`},
{target:`ギャンブラーの誤謬 (Gambler's fallacy)`, content:`個人的な主観によって確率論に基づいた予測を行わない傾向。`},
{target:`ナイーブ・リアリズム（Naive realism）`, content:`自分は、周りの世界を客観的に見ているが、自分と意見が合わない人は情報が少なく、非合理的で、偏っているに違いないと考える傾向。`},
{target:`双曲割引 （Hyperbolic discounting）`, content:`遠い将来なら待てるが、近い将来ならば待てない傾向。`},
{target:`後知恵バイアス（Hindsight bias）`, content:`物事が起きてからそれが予測可能だったと考える傾向。`},
{target:`間違った転移（Illicit transference）`, content:`ある言葉が分配的な意味（階級の各構成員を指す）と集合的な意味（階級そのものを全体として指す）のあいだに違いがないと思い込む間違い。`},
{target:`代表性ヒューリスティック（Representativeness heuristic）`, content:`あるものの代表的な特徴と合致しているならば、それに近いだろうと直感的に判断すること。`},
{target:`イケア効果（IKEA effect）`, content:`少しでも手間をかけて完成させると、出来上がった物への評価が創作者によってのみ高まる効果。`},
{target:`焦点錯覚（Focusing illusion）`, content:`最初に接した情報に引きずられ、物事の全体像ではなく一部分の側面しか見ようとしない傾向。（あなたがあることを考えているとき、人生においてそのこと以上に重要なことは存在しない）。`},
{target:`コントロール幻想（Illusion of Control bias）`, content:`実際には自分とは関係のない現象を自分がコントロールしていると錯覚すること。`},
{target:`妥当性の錯覚（Illusion of validity）`, content:`分析したデータに一貫性があると、仮説が正しかったと過大評価してしまう傾向。`},
{target:` 錯誤相関 （Illusory correlation）`, content:`関係がない２つの出来事に関係があると思い込んでしまう錯覚。`},
{target:`真理の錯誤効果 （Illusory truth effect）`, content:`間違った情報でも、何度も報道されているうちに本当だと考える効果。初めて知った主張よりも、既に知っている主張を正しいと考える傾向。`},
{target:`インパクトバイアス（Impact bias）`, content:`将来経験するであろう事件の心理的衝撃や長さを過大に推測する傾向。`},
{target:` ツァイガルニク効果（Zeigarnik effect）`, content:`人は達成できなかった事柄や中断している事柄のほうを、達成できた事柄よりもよく覚えているという現象。`},
{target:`情報バイアス（Information bias）`, content:`多くの情報を集めた方が正しい決定ができると考え、関係の無い情報を集めてしまう傾向。`},
{target:`理不尽な継続（Irrational escalation）`, content:`信じてコツコツと継続してきたことが、間違いだということが明らかになってもそれを継続してしまう傾向。`},
{target:` 道具の法則（Law of the instrument）`, content:`慣れ親しんだ道具に依存しすぎる傾向。`},
{target:`Less-is-better効果（Less-is-better effect）`, content:`別々に評価すると「少ない方」を選択するが、同時に評価すると「多い方」を選択する傾向。`},
{target:`損失嫌悪（Loss aversion）`, content:`同等の利益を得るよりも損失を回避することを好む傾向。`},
{target:`単純接触効果（Mere exposure effect）`, content:`繰り返し接すると好意度や印象が高まるという効果。しかし最適回数あり。`},
{target:`貨幣錯覚（Money illusion）`, content:`実質値ではなく名目値に基いて物事を判断してしまう傾向。`},
{target:`モラル・ライセンシング（moral licensing）`, content:`何か良いことをした人が、あまり良くないことをしても良いという許可を自分に与えることてしまうこと。`},
{target:`確率の無視（Neglect of probability）`, content:`不確かな状況下では、人が確率を完全に無視する傾向。`},
{target:`非適応的な選択の変更（Non-adaptive choice switching）`, content:`ある選択をした結果、悪い経験をするとその選択が最適だったのにも関わらず、再び同じ場面に出くわしたとき、最適だった以前した選択を避ける傾向。`},
{target:`女性は素晴らしい効果（Women are wonderful effect）`, content:`人は男性より女性に対して、よりポジティブな属性を連想する効果。`},
{target:`サンクコスト効果 (Sunk cost fallacy)`, content:`これまで費やした費用、時間、人命などが無駄になることを恐れて、それまでに行ってきた行為を正当化するために非合理的な判断をする傾向。「コンコルドの誤謬」とも言う。`},
{target:`何もしないバイアス（Omission bias ）`, content:`悪事を実際に行うほうが、何もしない結果、同じくらい悪い結果になることよりも罪深いと考える傾向。`},
{target:`楽観主義バイアス （Optimism bias）`, content:`悪い事は自分には起きないと考える傾向。うまく使えば幸福になる。`},
{target:`ダチョウ効果 （Ostrich effect）`, content:`明白な危機的状況を無視する傾向。`},
{target:`成果バイアス（Outcome bias）`, content:`ある出来事のプロセスを軽視し、結果のみに注目する傾向。`},
{target:`自信過剰効果（Overconfidence effect）`, content:`判断の主観的な自信が、客観的な実際の評価よりも高くなる傾向。`},
{target:`パレイドリア（Pareidolia）`, content:`そこに存在しないのに、よく知っているパターンをそこにあるように感じること。`},
{target:`ゼロサム・バイアス（zero-sum bias）`, content:`誰かが利益を得れば、誰かが損をすると考える傾向。`},
{target:`計画継続バイアス（Plan continuation bias）`, content:`状況の変化に直面しても既存の行動方針を継続させる傾向。`},
{target:`計画の誤謬（Planning fallacy）`, content:`計画の達成にかかる時間、コスト、リスクを過小評価する傾向。`},
{target:`現在志向バイアス（Present bias）`, content:`将来の大きな報酬を待つよりも、現在の小さな報酬で解決しようとする傾向。`},
{target:`植物無視（Plant blindness）`, content:`植物を無視する傾向。`},
{target:`投影バイアス（Projection bias）`, content:`今の感情や考えが、未来でも同じままであると思い込む傾向。感情予測（affective forecasting）に関連する。`},
{target:`イノベーション推進バイアス（Pro-innovation bias）`, content:`イノベーション万歳という思い込み。発明やイノベーション（技術革新）が社会的に有用であることに対して過度に楽観的である一方で、その限界や弱点を認識しない傾向。`},
{target:`比例バイアス（Proportionality Bias）`, content:`大きな出来事には大きな原因があると思い込む傾向。`},
{target:`擬似確信効果（Pseudocertainty effect）`, content:`いくつかの段階のある意思決定において、実際には不確実であるのに、結果が確実であると認識してしまう傾向。`},
{target:`韻踏み効果（Rhyme as reason effect）`, content:`韻を踏んだり似たような表現を繰り返すと説得力が増す効果。`},
{target:`特徴バイアス（Salience bias）`, content:`客観的には差がない項目であるにも関わらず、特徴的だったり、感情に訴える特徴がある項目に注目してしまい、特徴的ではない項目を無視していしまう傾向。`},
{target:`リスク補償 (Risk compensation）`, content:`リスクが高い時は安全な行動をするが、安全になるとリスクの高い行動を取る傾向。`},
{target:`スコープの無視`, content:`問題を扱うときに、その大きさに無頓着になる傾向。`},
{target:`選択的知覚 (Selective perception)`, content:`不愉快な情報や、それまでの信念に反する情報はすぐに忘れる傾向。`},
{target:`センメルヴェイス反射 (Semmelweis reflex)`, content:`通説にそぐわない新事実を拒絶する傾向。常識から説明できない事実を受け入れがたい傾向。`},
{target:`現状維持バイアス（Status quo bias）`, content:`何か問題が出ない限り、現状維持を望む傾向。`},
{target:`生存者バイアス`, content:`現在残っているものだけを基準として判断し、淘汰されたものについて考えない傾向。`},
{target:`システム正当化バイアス (System justification)`, content:`現状のやり方に例え問題があったとしても、未知のわけのわからないやり方を選択をするよりも、知っている現状のやり方を選択しようとする傾向。`},
{target:`時間節約バイアス (Time saving bias)`, content:`高速を出しているときに、さらにスピードを出して節約できるであろうと思う時間を過大評価する傾向。`},
{target:`パーキンソンの凡俗法則（Parkinson's law of triviality）`, content:`組織が些細な物事に対して、不釣り合いなほど重点を置く傾向。`},
{target:`ゼロリスクバイアス（Zero-risk bias）`, content:`ある問題の危険性を完全にゼロにする事に注意を集中し、他の重要な問題の危険性に注意を払わない。`},
{target:`社会的望ましさバイアス（Social desirability bias）`, content:`社会的に望ましい側面のみを報告し、望ましくない側面を報告しない傾向。`},
{target:`権威バイアス（Authority bias）`, content:`内容とは無関係でも、権威者の意見を評価し、その意見に影響される傾向。`},
{target:`バンドワゴン効果 (Bandwagon effect)`, content:`ある選択が多数に受け入れられているとき、その選択への支持が一層強くなる効果。`},
{target:`チアリーダー効果`, content:`集団内にいると個人が魅力的に見えるが、個人としてみると魅力が減る傾向。`},
{target:`グループシンク（Groupthink）`, content:`グループで考えると愚かな結論になってしまうこと。集団浅慮（しゅうだんせんりょ）とも呼ばれます。`},
{target:`ハロー効果（Halo effect）`, content:`ある対象を評価をするとき、目立った特徴に引きずられて他の特徴についての評価が歪められること。例：美人だと性格や知性が高いと思いこむ。`},
{target:`内集団バイアス (Ingroup bias）`, content:`自分が属している集団には好意的な態度をとり、外の集団には差別的な態度をとるバイアス。`},
{target:`公正世界仮説（Just-world hypothesis）`, content:`良いことは良い人に起こり、悪いことは悪い人に起こると考える傾向。`},
{target:`道徳的な運（Moral luck）`, content:`運の良し悪しを、道徳の良し悪しに結びつけて考える傾向。`},
{target:`NIH症候群（Not Invented Here Syndrome）`, content:`他の人や会社が開発したアイデアを採用したがらない傾向。`},
{target:`ピグマリオン効果（Pygmalion effect）`, content:`他人からの期待にそうようにパフォーマンスが向上する効果。`},
{target:`自己奉仕バイアス（Self-serving bias）`, content:`成功の要因は自分にし、失敗の要因は自分以外にあると考える傾向。`},
{target:`親近バイアス（Recency bias）`, content:`歴史的な出来事よりも最近の出来事を好む傾向。`},
{target:`グーグル効果（Google Effect）`, content:`インターネットで調べたことは、記憶に残りにくい傾向。`},
{target:`否定性バイアス (Negativity bias)`, content:`ポジティブな情報よりもネガティブな情報の方が、行動に強い影響を与える傾向。`},
{target:`ピーク・エンドの法則（Peak-end rule）`, content:`過去の経験をその時間や経過ではなく、その絶頂（ピーク）時にどうだったかと、どう終わったかだけで判断してしまう傾向。`},
{target:`正常性バイアス （Normalcy bias）`, content:`異常な状態にいるにも関わらず、それを正常だと認識することで強いストレスを感じないようにするバイアス。`},
{target:`反事実的思考（counterfactual thinking）`, content:`すでに起こった出来事に対して、実際に起こったこと違っていたり、逆のな選択肢を作り出す傾向。`},
]
